export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTRATION: '/registration',
  CATEGORIES: '/categories',
  CATEGORY: '/categories/:category',
  SUBCATEGORY: '/categories/:category/:subCategory',
  SEARCH: '/search',
  PRODUCT: '/categories/:category/:subCategory/:slug',
  SALE: '/sales',
  LEES_THEN: '/less_then_500',
  TRENDING: '/trending',
  PROFILE: '/profile',
  CART: '/cart',
};
